name: CI

on: [ push, workflow_dispatch ]

jobs:
  views:
    runs-on: hpretl/iic-osic-tools:latest
    name: Generate various views from MAG
    steps:
      - uses: actions/checkout@v4
      - name: Generate views
        working-directory: ./pdk/libs.ref/gf180mcu_as_sc_mcu7t3v3
        run: make views
      - name: Tarball SCL
        run: |
          tar -cf /tmp/scl.tar -C . .
      - name: Upload SCL Tarball
        uses: actions/upload-artifact@v4
        with:
          name: scl-tarball
          path: /tmp/scl.tar
