name: CI

on: [ push, workflow_dispatch ]

jobs:
  views:
    runs-on: ubuntu-latest
    name: Generate various views from MAG
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
      - name: Install required packages
        run: |
          sudo apt-get update && sudo apt-get install -y klayout
          pip3 install klayout
      - uses: ./.github/actions/build_magic
      - uses: actions/checkout@v4
      - name: Clone PDK
        working-directory: ./example_project
        run: make clone-pdk
      - name: Setup environment variables for magic
        run: |
          echo "PDK_ROOT=$(pwd)/example_project/gf180mcu_pdk" >> $GITHUB_ENV
          echo "PDK=gf180mcuD" >> $GITHUB_ENV
      - name: Generate views
        working-directory: ./pdk/libs.ref/gf180mcu_as_sc_mcu7t3v3
        run: make views
      - name: Upload SCL artifact
        uses: actions/upload-artifact@v4
        with:
          name: scl-tarball
          path: pdk/*
